### ISSUE TITLE
Reconsider progress messages in functions

### ISSUE THREAD

**Issue by joeroe** [eweaverdyck/nearpresence#1]
`IDW_nnear()`, `IDW_radius()` and `NP()` all print several progress messages to the console. This makes sense in interactive use but can be a bit annoying if they are embedded in a script or Rmd. Consider:

* At least with the example data, the IDW functions are quick to execute for me, so maybe the messages here aren't really necessary?
* Adding a `quiet` or `verbose` option that suppresses/enables the messages
* Messages should be printed with `message()` rather than `print()`, so they can be properly formatted and the user can control them with e.g. `suppressMessages({ ... })` or `message=FALSE` in RMarkdown.

**Comment by eweaverdyck** [comment]
Thanks, Joe! I've added a `verbose` parameter to each function and suppressed the messages in the README and the vignette.
